-- Luong dat coc HomeStay Dorm. Chay file nay trong Supabase SQL Editor.
alter table public."DatCoc"
  add column if not exists "LoaiThue" text default 'GIUONG_LE',
  add column if not exists "MaPhong" bigint,
  add column if not exists "MaCN" bigint,
  add column if not exists "NVSale" bigint,
  add column if not exists "SoGiuongThue" integer default 1,
  add column if not exists "BatDauThanhToan" timestamptz,
  add column if not exists "DatCocThanhCong" timestamptz,
  add column if not exists "LyDoXuLy" text,
  add column if not exists "CapNhatLuc" timestamptz default now();

create table if not exists public."KhoaGiuongDatCoc" (
  "MaGiuong" bigint primary key references public."Giuong"("MaGiuong") on delete cascade,
  "MaDatCoc" bigint not null references public."DatCoc"("MaDatCoc") on delete cascade,
  "KhoaLuc" timestamptz not null default now(),
  "HetHanLuc" timestamptz
);

create index if not exists "KhoaGiuongDatCoc_MaDatCoc_idx"
  on public."KhoaGiuongDatCoc"("MaDatCoc");

create table if not exists public."ChungTuDatCoc" (
  "MaChungTu" bigint generated by default as identity primary key,
  "MaDatCoc" bigint not null references public."DatCoc"("MaDatCoc") on delete cascade,
  "MaGiaoDich" text,
  "HinhAnhDataUrl" text,
  "NguoiTaiLen" bigint,
  "TaiLenLuc" timestamptz not null default now(),
  "TrangThai" text not null default 'CHO_XAC_NHAN',
  constraint "ChungTuDatCoc_co_bang_chung" check (
    nullif(btrim(coalesce("MaGiaoDich", '')), '') is not null
    or nullif(btrim(coalesce("HinhAnhDataUrl", '')), '') is not null
  )
);

create table if not exists public."LichSuDatCoc" (
  "MaLichSu" bigint generated by default as identity primary key,
  "MaDatCoc" bigint not null references public."DatCoc"("MaDatCoc") on delete cascade,
  "TrangThaiCu" text,
  "TrangThaiMoi" text not null,
  "NguoiThucHien" bigint,
  "VaiTroThucHien" text not null,
  "GhiChu" text,
  "ThoiDiem" timestamptz not null default now()
);

create index if not exists "LichSuDatCoc_MaDatCoc_idx"
  on public."LichSuDatCoc"("MaDatCoc", "ThoiDiem" desc);

create table if not exists public."ThongBaoDatCoc" (
  "MaThongBao" bigint generated by default as identity primary key,
  "MaDatCoc" bigint not null references public."DatCoc"("MaDatCoc") on delete cascade,
  "NguoiNhan" bigint,
  "VaiTroNhan" text,
  "NoiDung" text not null,
  "DaDoc" boolean not null default false,
  "TaoLuc" timestamptz not null default now(),
  constraint "ThongBaoDatCoc_co_nguoi_nhan" check (
    "NguoiNhan" is not null or "VaiTroNhan" is not null
  )
);

create index if not exists "ThongBaoDatCoc_chua_doc_idx"
  on public."ThongBaoDatCoc"("DaDoc", "NguoiNhan", "VaiTroNhan");

